- repo: https://github.com/pycqa/isort
  rev: 5.5.2
  hooks:
    - id: isort
      args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3